USE [master]
GO

IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'mySandbox')
DROP DATABASE [mySandbox]
GO

USE [master]
GO

/****** Object:  Database [mySandbox]    Script Date: 05/15/2018 15:18:35 ******/
CREATE DATABASE [mySandbox] --ON  PRIMARY 
GO
/* ( NAME = N'mySandbox', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\mySandbox.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'mySandbox_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\mySandbox_log.LDF' , SIZE = 504KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
*/

ALTER DATABASE [mySandbox] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [mySandbox].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

--ALTER DATABASE [mySandbox] SET ANSI_NULL_DEFAULT OFF 
--GO

--ALTER DATABASE [mySandbox] SET ANSI_NULLS OFF 
--GO

--ALTER DATABASE [mySandbox] SET ANSI_PADDING OFF 
--GO

--ALTER DATABASE [mySandbox] SET ANSI_WARNINGS OFF 
--GO

--ALTER DATABASE [mySandbox] SET ARITHABORT OFF 
--GO

--ALTER DATABASE [mySandbox] SET AUTO_CLOSE OFF 
--GO

--ALTER DATABASE [mySandbox] SET AUTO_CREATE_STATISTICS ON 
--GO

--ALTER DATABASE [mySandbox] SET AUTO_SHRINK OFF 
--GO

--ALTER DATABASE [mySandbox] SET AUTO_UPDATE_STATISTICS ON 
--GO

--ALTER DATABASE [mySandbox] SET CURSOR_CLOSE_ON_COMMIT OFF 
--GO

--ALTER DATABASE [mySandbox] SET CURSOR_DEFAULT  GLOBAL 
--GO

--ALTER DATABASE [mySandbox] SET CONCAT_NULL_YIELDS_NULL OFF 
--GO

--ALTER DATABASE [mySandbox] SET NUMERIC_ROUNDABORT OFF 
--GO

--ALTER DATABASE [mySandbox] SET QUOTED_IDENTIFIER OFF 
--GO

--ALTER DATABASE [mySandbox] SET RECURSIVE_TRIGGERS OFF 
--GO

--ALTER DATABASE [mySandbox] SET  DISABLE_BROKER 
--GO

--ALTER DATABASE [mySandbox] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
--GO

--ALTER DATABASE [mySandbox] SET DATE_CORRELATION_OPTIMIZATION OFF 
--GO

--ALTER DATABASE [mySandbox] SET TRUSTWORTHY OFF 
--GO

--ALTER DATABASE [mySandbox] SET ALLOW_SNAPSHOT_ISOLATION OFF 
--GO

--ALTER DATABASE [mySandbox] SET PARAMETERIZATION SIMPLE 
--GO

--ALTER DATABASE [mySandbox] SET READ_COMMITTED_SNAPSHOT ON 
--GO

--ALTER DATABASE [mySandbox] SET HONOR_BROKER_PRIORITY OFF 
--GO

--ALTER DATABASE [mySandbox] SET  READ_WRITE 
--GO

--ALTER DATABASE [mySandbox] SET RECOVERY FULL 
--GO

--ALTER DATABASE [mySandbox] SET  MULTI_USER 
--GO

--ALTER DATABASE [mySandbox] SET PAGE_VERIFY CHECKSUM  
--GO

--ALTER DATABASE [mySandbox] SET DB_CHAINING OFF 
--GO


